---
version: '3.6'

x-quorum-def:
  &quorum-def
  restart: "on-failure"
  image: ott-quorum:latest
  build:
    context: ./
    args:
      QUORUM_VERSION: ${QUORUM_VERSION:-latest}
  expose:
    - 30303
    - 8545
    - 9545
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 3s
    timeout: 3s
    retries: 10
    start_period: 5s

services:

  validator0:
    << : *quorum-def
    ports:
      - 21000:8545/tcp
      - 30303
      - 9545
    environment:
      - GOQUORUM_CONS_ALGO=qbft
    volumes:
      - ./data/quorum/validator0:/data
      - ./logs/quorum:/var/log/quorum/
    networks:
      ott-network:
        ipv4_address: 172.16.239.10

  validator1:
    << : *quorum-def
    ports:
      - 21001:8545/tcp
      - 30303
      - 9545
    environment:
      - GOQUORUM_CONS_ALGO=qbft
    volumes:
      - ./data/quorum/validator1:/data
      - ./logs/quorum:/var/log/quorum/
    networks:
      ott-network:
        ipv4_address: 172.16.239.11

  validator2:
    << : *quorum-def
    ports:
      - 21002:8545/tcp
      - 30303
      - 9545
    environment:
      - GOQUORUM_CONS_ALGO=qbft
    volumes:
      - ./data/quorum/validator2:/data
      - ./logs/quorum:/var/log/quorum/
    networks:
      ott-network:
        ipv4_address: 172.16.239.12

  validator3:
    << : *quorum-def
    ports:
      - 21003:8545/tcp
      - 30303
      - 9545
    environment:
      - GOQUORUM_CONS_ALGO=qbft
    volumes:
      - ./data/quorum/validator3:/data
      - ./logs/quorum:/var/log/quorum/
    networks:
      ott-network:
        ipv4_address: 172.16.239.13

networks:
  ott-network:
    name: ott-network
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
